"""empty message

Revision ID: 2020195ab737
Revises: 
Create Date: 2026-01-16 20:04:21.171025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2020195ab737'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticker_prices_ticker', 'ticker_prices', ['ticker'], unique=False)
    op.create_index('ix_ticker_prices_ticker_timestamp', 'ticker_prices', ['ticker', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticker_prices_ticker_timestamp', table_name='ticker_prices')
    op.drop_index('ix_ticker_prices_ticker', table_name='ticker_prices')
    op.drop_table('ticker_prices')
    # ### end Alembic commands ###
